import TzBanner from "@/components/TzBanner";
import TzSwiper from "@/components/TzSwiper";
import Banner from "@/components/ui/Banner";
import TzCarousel from "@/components/TzCarousel";
import { Metadata } from "next";
import Image from "next/image";
import TzPageProgress from "@/components/TzPageProgress";
export const metadata: Metadata = {
  title: "Create Next App home",
  description: "Generated by create next app",
};

export default function () {
  return (
    <div className="financial-services " style={{ height: `calc(100vh - 3.5rem)` }}>
      <Banner></Banner>
      {/* <TzBanner></TzBanner> */}
    </div>
  );
}
