import Banner from "@/components/ui/Banner";
import { Metadata } from "next";
import Image from "next/image";
export const metadata: Metadata = {
  title: "Create Next App home",
  description: "Generated by create next app",
};

export default function () {
  return (
    <div className="financial-services">
      <Banner></Banner>
    </div>
  );
}
