import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/globals.css";

const lf = localFont({
  src: [
    {
      path: "../../public/fonts/GeistVF.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/GeistMonoVF.woff",
      weight: "400",
      style: "normal",
    },
  ],
  display: "swap", // 字体显示策略
});
export const metadata: Metadata = {
  title: "Create Next App45623",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lf.className}  antialiased`}>{children}</body>
    </html>
  );
}
